### PR TITLE
Update clash.js

### PR DESCRIPTION
**Pull request by AustinGallippo**
Updated clash.js to show that Clash counters Montagne.

#63

### CODE REVIEW

**Comment by AustinGallippo** [comment]
@BurkusCat Any updates on this?

**Comment by BurkusCat** [comment]
Hey @AustinGallippo , I added a small review comment previously, are you able to see it? If you are able to make that change I will approve and merge :)

Thank you for the PR!

**Comment by AustinGallippo** [comment]
Hey, I'm sorry @BurkusCat I'm unable to see that review message. Though I may just be unaware to look for it as I'm newer to open source contributions. Thank you for the response.

**Comment by BurkusCat** [comment]
No worries, I'll add it as a comment (I'm on my phone so can't tell if I've done something wrong 😅):

`Can we update the text to be "Montagne is more susceptible to shocks from Clash's CCE Shield.", please?`

**Comment by AustinGallippo** [comment]
@BurkusCat Alrighty, I updated the file with the text you wanted!

**Review by BurkusCat — APPROVED** [review]
Looks good, thank you for making the change! 😃

**Comment by AustinGallippo** [comment]
@BurkusCat You're welcome, have a great day.

**Pull request merged**
