### PR TITLE
Run-able with more modern version of npm and node (npm 10.2.4, node 20.11.0)

### PR DESCRIPTION
**Pull request by lilyhuang-github**
I update some deprecated dependencies and updated file path from cjs syntax to esm syntax.
This would solve issue #207 . 
It would still use a lot of changing but it runs.

### CODE REVIEW

**Comment by lilyhuang-github** [comment]
I an instance of thorn but she isn't showing up so I'm not sure why currently but I can add the rest of the new operators and potentially their counters

**Comment by lilyhuang-github** [comment]
Nvm. I figured it out. I'm gonna add the rest of the new operators and then maybe their counters.

**Comment by BurkusCat** [comment]
Changes look really good! Thank you for contributing @lilyhuang-github !

Perhaps the minimum node version could be raised to v20.17.0 on the README now with the changes you have made?

**Review by BurkusCat — APPROVED** [review]

**Comment by lilyhuang-github** [comment]
No problem. I'll update the README alongwith adding the new operators and their counters.

**Pull request merged**
