### PR TITLE
gulp bug fixed

### PR DESCRIPTION
**Pull request by abuDarda97**

### CODE REVIEW

**Comment by CrayCrayDecay** [comment]
Hi Abu,

Thank you for working on this. Unfortunately, I do not have my development computer with me at the moment, so I am unable to test. I will refer this to @BurkusCat for testing.

**Comment by BurkusCat** [comment]
Thanks Abu!

I'm lacking a PC too Alex haha! I'l take a look at it on Friday :)

**Comment by abuDarda97** [comment]
Haha no worries :)

**Comment by BurkusCat** [comment]
Apologies about this guys. I should have taken a look at this.

Thanks Alex for reviewing it.

**Pull request merged**
