### PR TITLE
Switch to pngs

### PR DESCRIPTION
**Pull request by BurkusCat**
- I noticed a small performance improvement when switching to using .pngs by default #156 
- I've added an option to switch to viewing high detail .svgs in the graph (lower framerate)
- I've changed the background to be a Void Edge background
- I've removed the alpha decay so the simulation will last longer (works better with the performance improvements)

### CODE REVIEW

**Comment by Mr-Martinez** [comment]
I think the speed got worst somehow. I'm not sure  if I need to do something extra.

This is what I have when running the png version: 
png-stats


This is what I have when running the website:
svg-stats


I also have an initial lag of about 1-4 seconds of lag, even thought the website loads just as fast, sometimes faster than the website.

**Comment by Mr-Martinez** [comment]
Is there no lag when you run on your environment?

**Comment by BurkusCat** [comment]
Hmmm, so the .pngs when in dev mode are 1500x1500 pixels. Whenever they are built for production, they will be scaled down to 500x500 which should help a bit with load time and smoothness.

Are the graphs you have posted from initial load of the website? Even the 500x500 pngs will be larger in file size compared to the .svgs so I'd expect the load time to be longer. How do you find the framerate when dragging around the .pngs vs dragging around the .svgs? I find the .pngs to be much smoother.

**Comment by Mr-Martinez** [comment]
I tried testing on other browsers, it seems that on Safari, there is a huge spike on loading.
When I run on Firefox, no issues. None at all, it's the strangest.

On Firefox, its nice, fast, smooth (dragging everything).

On Safari it's almost unworkable. Can't drag, or rather I need to click twice to drag.

Are you having issues running on Safari?

**Comment by BurkusCat** [comment]
Interesting! I've been testing on Chrome (and Chrome on Android on the live site). So the live site with the .svgs works well for you in Safari desktop + mobile? But with .pngs, desktop Safari doesn't work very well?

On Firefox, are the .pngs smoother for you?

I was thinking that I could potentially do a browser check for Safari desktop. Then after the PR is merged, if .pngs are bad for Safari mobile I will do the same for it. Thoughts?

**Comment by Mr-Martinez** [comment]
Yes, on Firefox, everything is smooth!

It could just be how safari handles loading.
Let me take a look at this, a check for browser is a fix but maybe there is a way to reduce loading time? 

Fixing loading time will be a huge benefit in the long run. I’m thinking it has to do with images as that’s the only change.

It seems safari freaks out at 70%+.

I’m going to take a look at this tonight. 
I need a break from the beat down that is grammar lol!

Best Regards,

**Comment by Mr-Martinez** [comment]
Looking at the code more, I see that code is slowing down due to d3.min.js

```
function kn(t) {
     if (!cl) {
         sl && (sl = clearTimeout(sl));
         t - pl > 24 ? (t < 1 / 0 && (sl = setTimeout(Tn, t - vl.now() - dl)), fl && (fl = clearInterval(fl))) : (fl || (hl = vl.now(), fl = setInterval(Nn, ll)), cl = 1, gl(Tn))
     }
 }
```

The animation calls is what is slowing down computer when updating this line of code (specifically the transform section x/y axis):

``
<g class="node node-image" transform="translate(1081.4827176028746, 154.08614521913478)"><image height="70px" x="-35px" NS1:href="img/png/alibi.png" y="-35px" width="70px"></image></g>
``


> I was thinking that I could potentially do a browser check for Safari desktop

I think this is the best course of action, I can't think of anything else.
If not I can merge the pull request, maybe it behaves differently once on the server.

**Pull request merged**
